-- Generated by ChatGPT from four-connect.py

local ROWS = 6
local COLS = 7
local arr = {}

-- Initialize the game board
for i = 1, ROWS do
    arr[i] = {}
    for j = 1, COLS do
        arr[i][j] = "0"
    end
end

-- Function to print the game board
function printBoard()
    for i = 1, ROWS do
        for j = 1, COLS do
            io.write(arr[i][j] .. " ")
        end
        print()
    end
end

-- Function to place a coin in a column
function placeCoin(col, coin)
    local row = 1
    while row < ROWS and arr[row + 1][col] == "0" do
        row = row + 1
    end

    if arr[row][col] == "0" then
        arr[row][col] = coin
        return true
    else
        print("Column is full, try again")
        return false
    end
end

-- Function to check for a draw
function checkDraw()
    for i = 1, ROWS do
        for j = 1, COLS do
            if arr[i][j] == "0" then
                return false
            end
        end
    end
    return true
end

-- Function to check if a player has won
function checkIsWinner(coin)
    -- Check horizontally
    for i = 1, ROWS do
        for j = 1, COLS - 3 do
            if arr[i][j] == coin and arr[i][j + 1] == coin and arr[i][j + 2] == coin and arr[i][j + 3] == coin then
                return true
            end
        end
    end

    -- Check vertically
    for i = 1, ROWS - 3 do
        for j = 1, COLS do
            if arr[i][j] == coin and arr[i + 1][j] == coin and arr[i + 2][j] == coin and arr[i + 3][j] == coin then
                return true
            end
        end
    end

    -- Check diagonally (up-right)
    for i = 1, ROWS - 3 do
        for j = 1, COLS - 3 do
            if arr[i][j] == coin and arr[i + 1][j + 1] == coin and arr[i + 2][j + 2] == coin and arr[i + 3][j + 3] == coin then
                return true
            end
        end
    end

    -- Check diagonally (up-left)
    for i = 1, ROWS - 3 do
        for j = 4, COLS do
            if arr[i][j] == coin and arr[i + 1][j - 1] == coin and arr[i + 2][j - 2] == coin and arr[i + 3][j - 3] == coin then
                return true
            end
        end
    end

    return false
end

-- Function to play the game
function play()
    local currentTurn = "R"
    while true do
        print("It's " .. currentTurn .. " Turn:")
        printBoard()

        local columnInput
        while true do
            io.write("Pick a column to place the coin (0-6): ")
            columnInput = io.read("*n")

            if columnInput and columnInput >= 0 and columnInput <= COLS and arr[1][columnInput + 1] == "0" then
                break
            else
                print("Invalid input. Please try again.")
            end
        end

        columnInput = columnInput + 1 -- Adjust for Lua indexing starting from 1
        local isPlaced = placeCoin(columnInput, currentTurn)

        if isPlaced then
            if checkIsWinner("Y") then
                print("Y won the game!")
                printBoard()
                break
            elseif checkIsWinner("R") then
                print("R won the game!")
                printBoard()
                break
            elseif checkDraw() then
                print("DRAW!")
                printBoard()
                break
            end

            currentTurn = (currentTurn == "Y") and "R" or "Y"
        end
    end
end

-- Run the game
play()
